# docker-compose.yml

version: '3.1'

services:
  nginx:
    image: nginx:1.19.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./var/www/public:/var/www/public
    ports:
      - '18080:80'